##########################################################
################### 日志配置Start  ###################
##########################################################
logging: 
 level:
  root: warn
  org:
   springframework:
    web: debug
##########################################################
################### 日志配置End ###################
##########################################################

##########################################################
################### thymeleaf配置Start  ###################
##########################################################  
    #thymeleaf start
spring:
 thymeleaf:
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  #开发时关闭缓存,不然没法看到实时页面
  cache: false
#thymeleaf end
##########################################################
################### thymeleaf配置End ###################
##########################################################  
